"""Render FM_QUALITY_TABLE.md (all models) from fm_quality.jsonl. FM_QUALITY.md (hand-written) links to it."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
rows = [json.loads(l) for l in open(os.path.join(HERE, "fm_quality.jsonl"))]
order = {"good-to-evolve": 0, "usable-with-caveats": 1, "avoid": 2}
rows.sort(key=lambda r: (order.get(r.get("rating"), 3), r["model"].lower()))


def f(v, nd=2):
    if v is None:
        return ""
    if isinstance(v, bool):
        return "yes" if v else "NO"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


hdr = ["model", "rating", "type", "trim (method)", "alpha", "thr cmd", "gear", "hold10 dθ/dKCAS", "doublet peak q / nz",
       "q decay", "q gain °/s/unit", "pitch step: pass, err°, ovs°, t90 s", "det", "RTF pure/loop", "reasons"]
lines = ["# FM quality: per-model table (generated by make_fm_report.py from fm_quality.jsonl)", "",
         "Conditions: JSBSim 1.3.1, dt 1/120 s, gear commanded UP before trim (fixed-gear models unaffected), mixture 1, "
         "engines set-running. RTF measured with 6 concurrent worker processes on the shared box (single-process RTF is higher). "
         "Gear-down results from the earlier run: fm_quality_geardown.csv.", "",
         "| " + " | ".join(hdr) + " |", "|" + "---|" * len(hdr)]
for r in rows:
    trim = f"{f(r.get('trim_kcas'),0)} KCAS / {f(r.get('trim_alt_ft'),0)} ft ({r.get('trim_method')})" if r.get("trim_kcas") else r.get("trim_method", "")
    ps = f"{f(r.get('pstep_pass'))}, {f(r.get('pstep_final_err_deg'))}, {f(r.get('pstep_overshoot_deg'))}, {f(r.get('pstep_t90_s'))}" if r.get("pstep_status") else ""
    lines.append("| " + " | ".join([
        r["model"], r.get("rating", ""), r.get("real_type", "") or r.get("category", ""), trim, f(r.get("alpha_deg")), f(r.get("throttle"), 3),
        f(r.get("gear_pos"), 0), f"{f(r.get('hold10_dtheta_deg'))} / {f(r.get('hold10_dkcas'))}" if "hold10_dtheta_deg" in r else "",
        f"{f(r.get('doublet_peak_q_dps'))} / {f(r.get('doublet_peak_nz'))}" if r.get("doublet_status") else "",
        f(r.get("q_decay_ratio"), 3), f(r.get("pitch_rate_gain_dps_per_unit")), ps, f(r.get("deterministic")),
        f"{f(r.get('rtf_pure'),0)} / {f(r.get('rtf_loop'),0)}" if r.get("rtf_pure") else "",
        "; ".join(r.get("reasons", []))[:160].replace("|", "/")]) + " |")
open(os.path.join(HERE, "FM_QUALITY_TABLE.md"), "w").write("\n".join(lines) + "\n")
cnt = {}
for r in rows:
    cnt[r.get("rating")] = cnt.get(r.get("rating"), 0) + 1
print(cnt)
