"""Export the shared Phase-1 set (aircraft_profiles/phase1_shared.json) as an Evolution Runner profile block.

Writes JSON that can be pasted into an evolution/ batch config ("profiles" + "aircraft"). Every key is one that
evolution/sim.py's Profile accepts (heading hold landed in evolution/ at 05:33 PT, configs/phase1_hdg.json).
Two files:
  exports/evolution_phase1_profiles.json     v4 = the current Phase-1 default (phase1_v4 / phase1_default)
  exports/evolution_phase1_v5_profiles.json  v5 candidate: v4 + hold-quality term + downdraft scenario; the extra keys
                                             are listed in "_needs_code" (HANDOFF_phase1_v5.md)
Never writes into evolution/.

Usage: $PY export_shared_profiles.py [--out exports/evolution_phase1_profiles.json] [--out-v5 exports/evolution_phase1_v5_profiles.json]
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import adapter  # noqa: E402
import profiles as P  # noqa: E402

EVO_MODEL = {"c172x": "c172x", "t38": "T38", "b737": "737"}


FD_ROOT = "flight-dynamics/jsbsim_root"  # relative to flight_sim_3d/ (evolution resolves it against that dir)

# Heading-hold keys (HANDOFF_heading_hold.md; implemented in evolution/ since 05:33 PT).
HEADING_KEYS = ("heading_hold", "bank_limit_deg", "hdg_i_limit_deg", "w_heading", "hdg_rms_ref_deg")
HEADING_GENES = ("kp_hdg", "ki_hdg")


def evolution_profiles():
    sh = P.load_shared()
    t = sh["task"]
    hh_t = t["heading_hold"]
    profs, aircraft = {}, []
    for name, a in sh["aircraft"].items():
        task = adapter.load_task("phase1_v4", {"aircraft": name})
        fx = task.sim_fixed  # profile-scaled helper loops, full precision (rounding moved costs by ~1e-7)
        w = t["fitness_weights"]
        bounds = {**a["gain_bounds"], **a.get("heading_hold", {}).get("gain_bounds", {})}
        hh_on = bool(a.get("heading_hold", {}).get("enabled"))
        prof = {
            "_why": f"generated from genome/aircraft_profiles/phase1_shared.json ({name}) by genome/export_shared_profiles.py; "
                    "see genome/ALIGNMENT.md and genome/HANDOFF_heading_hold.md",
            "h0_ft": a["trim_alt_ft"], "speed_kts": a["trim_kcas"], "duration_s": t["duration_s"],
            "steps_rel_ft": t["steps_rel_ft"],
            "min_agl_ft": t["envelope_common"]["min_agl_ft"], "min_kcas": a["min_kcas"],
            "max_abs_theta_deg": t["envelope_common"]["max_abs_theta_deg"], "max_abs_phi_deg": t["envelope_common"]["max_abs_phi_deg"],
            "nz_limits": a["nz_limits"], "max_alt_err_ft": t["max_alt_err_ft"],
            "pitch_cmd_limits_deg": a["pitch_cmd_limits_deg"],
            "alt_i_limit_deg": t["controller_common"]["alt_i_limit_deg"], "pitch_i_limit": t["controller_common"]["pitch_i_limit"],
            "thr_kp": fx.get("kp_spd", 0.05), "thr_ki": fx.get("ki_spd", 0.01),
            "throttle_max": a["throttle_max"] if a["throttle_max"] is not None else 1.0,
            "throttle_all_engines": True, "gear_up": True,
            "alt_err_scale_ft": t["alt_err_scale_ft"], "itae_t0_s": t["itae_t0_s"], "itae_cap_s": t["itae_cap_s"],
            "w_effort": w["effort"] / w["track_alt"],
            "gain_bounds": {g: [b["min"], b["max"]] for g, b in bounds.items()},
            "ramp_fpm": t["ramp_fpm"], "ramp_accel_g": t["ramp_accel_g"], "alt_ref_ff": t["alt_ref_ff"],
            "w_comfort": w.get("comfort", 0.0) / w["track_alt"], "comfort_params": dict(t["comfort_params"]),
            "gene_kinds": {g: b["scale"] for g, b in bounds.items() if b["scale"] != "log"},
            "roll_kp": fx.get("kp_roll", 0.05), "roll_kd": fx.get("kd_roll", 0.02),
            "aircraft_root": FD_ROOT,
            # --- heading hold (needs the evolution/ code change in HANDOFF_heading_hold.md) ---
            "heading_hold": hh_on,
            "bank_limit_deg": a["heading_hold"]["bank_limit_deg"],
            "hdg_i_limit_deg": hh_t["hdg_i_limit_deg"],
            "w_heading": hh_t["weight"] / w["track_alt"],
            "hdg_rms_ref_deg": hh_t["hdg_rms_ref_deg"],
        }
        pname = f"phase1_{EVO_MODEL[name]}"
        profs[pname] = prof
        aircraft.append({"name": EVO_MODEL[name], "profile": pname})
    return {
        "_comment": "Shared Phase-1 set for evolution/ (generated by genome/export_shared_profiles.py from "
                    "genome/aircraft_profiles/phase1_shared.json). Paste 'profiles' and 'aircraft' into a batch config.",
        "_needs_code": {
            "profile_keys": [],
            "genes": [],
            "what": "nothing: the heading-hold keys/genes (genome/HANDOFF_heading_hold.md) are implemented in evolution/ "
                    "(configs/phase1_hdg.json). This file is the v4 Phase-1 default; v5 is in evolution_phase1_v5_profiles.json.",
        },
        "profiles": profs, "aircraft": aircraft,
    }


# v5 keys evolution/sim.py does not accept yet (HANDOFF_phase1_v5.md lists the code change for each).
V5_KEYS = ("w_hold", "hold_ref_ft", "hold_settle_s", "disturbance_scenario")


def evolution_v5_profiles():
    """v4 export + the v5 keys. Everything else is identical to evolution_profiles() (= phase1_v4)."""
    sh = P.load_shared()
    v5 = sh["task"]["v5"]
    hq, dist = v5["hold_quality"], v5["disturbance"]
    out = evolution_profiles()
    for name, a in sh["aircraft"].items():
        prof = out["profiles"][f"phase1_{EVO_MODEL[name]}"]
        task = adapter.load_task("phase1_v5", {"aircraft": name})
        assert task.fitness.weights["hold_osc"] == hq["weight"] and task.disturbance["downdraft_fps"] == a["disturbance"]["downdraft_fps"]
        prof["_why"] = prof["_why"].replace("HANDOFF_heading_hold.md", "HANDOFF_heading_hold.md and genome/HANDOFF_phase1_v5.md")
        prof.update({
            # --- v5 (needs the evolution/ code change in HANDOFF_phase1_v5.md) ---
            "w_hold": hq["weight"] / sh["task"]["fitness_weights"]["track_alt"],
            "hold_ref_ft": hq["hold_ref_ft"],
            "hold_settle_s": hq["hold_settle_s"],
            "disturbance_scenario": {"downdraft_fps": a["disturbance"]["downdraft_fps"], "onset_t_s": dist["onset_t_s"],
                                     "onset_ramp_s": dist["onset_ramp_s"], "steps_rel_ft": dist["steps_rel_ft"]},
        })
    out["_comment"] = out["_comment"].replace("Shared Phase-1 set", "Shared Phase-1 set, v5 candidate (phase1_v5),")
    out["_needs_code"] = {
        "profile_keys": list(V5_KEYS), "genes": [],
        "what": "hold-quality cost term (w_hold * RMS(e - window mean)/hold_ref_ft over the hold windows) and one extra "
                "calm scenario with a sustained 1-cos downdraft, appended after the 3 standard scenarios (mean of 4); "
                "see genome/HANDOFF_phase1_v5.md. Not the default: phase1_v4 (evolution_phase1_profiles.json) is.",
    }
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(HERE, "exports", "evolution_phase1_profiles.json"))
    ap.add_argument("--out-v5", default=os.path.join(HERE, "exports", "evolution_phase1_v5_profiles.json"))
    a = ap.parse_args(argv)
    for path, fn in ((a.out, evolution_profiles), (a.out_v5, evolution_v5_profiles)):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        json.dump(fn(), open(path, "w"), indent=2)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
